#!/bin/bash
# A script to run a specific case
# by Kalev Kalda Sikes

# note: this documentation assumes you know next to nothing about bash scripts
# note: not intended to be called from anything but the tools/testSection script

outputFolder="results"
if [ $# -gt 2 ];then
	outputFolder=$3
fi

dataFolder="resources"
if [ $# -gt 3 ];then
	dataFolder=$4
fi

if [ $# -gt 1 ]
then
	section=$1
	code=$2
	casepath=tests/$section/$code
	mkdir -p $outputFolder
	echo -en "TC: $section/$code; Data: '$dataFolder'; Output: '$outputFolder'\n"
	touch $outputFolder/$code.dtf
	./nts-client $dataFolder/data.cua $dataFolder/data.atf \
		$outputFolder/$code.dtf \
		< $casepath.input \
		&> $outputFolder/$code.output
	echo -en \
		" ===========================\n"\
		"$casepath\n"\
		"===========================\n"\
		 > $outputFolder/$code.output.diff
	diff \
		$casepath.output $outputFolder/$code.output \
		&> $outputFolder/$code.output.diff
	echo -en \
		"===========================\n"\
		"$casepath\n"\
		"===========================\n"\
		 > $outputFolder/$code.dtf.diff
	diff \
		$casepath.dtf $outputFolder/$code.dtf \
		&> $outputFolder/$code.dtf.diff
else
	echo -en "not enough arguments\n"
fi